### ISSUE TITLE
Editing Multisite

### ISSUE THREAD

**Issue by LeoSeabra** [admin-2020/Admin-2020-Theme#13]
No spacing or | between menus.

![2020-05-17_16h20_14](https://user-images.githubusercontent.com/65295381/82152711-1b8ea300-985b-11ea-9682-ea1bbe04de67.jpg)

**Comment by admin-2020** [comment]
Is this a WP Ultimo page?

**Comment by LeoSeabra** [comment]
No, it's when you edit a site on the super admin multisite area.

Visit | Panel

Information | Users | Themes | Options

**Comment by admin-2020** [comment]
Ah! Yeah this has been fixed in version 1.1.7 which is being uploaded today!
