### ISSUE TITLE
Couple bugs.

### ISSUE THREAD

**Issue by jointlymedia** [admin-2020/Admin-2020-Theme#14]
<img width="2560" alt="Schermafbeelding 2020-05-18 om 16 20 26" src="https://user-images.githubusercontent.com/64583736/82223841-7e4b7180-9923-11ea-881c-fbdff9798497.png"> - The ACF group/tabs are not ready in dark mode. 

<img width="2560" alt="Schermafbeelding 2020-05-18 om 16 21 18" src="https://user-images.githubusercontent.com/64583736/82223944-9de29a00-9923-11ea-9907-6785d469c77a.png"> - The text field is also not ready for dark mode. I believe it is on any Post type.

<img width="2560" alt="Schermafbeelding 2020-05-18 om 16 25 28" src="https://user-images.githubusercontent.com/64583736/82224514-32e59300-9924-11ea-995d-41bb49dac549.png"> - Oxygen settings page doesn't work that great.

- Put in SVG support for Admin Logo

**Comment by admin-2020** [comment]
All of these should be fixed in version 1.1.8 now

**Comment by jointlymedia** [comment]
<img width="1983" alt="Schermafbeelding 2020-05-25 om 12 15 19" src="https://user-images.githubusercontent.com/64583736/82803803-7048a400-9e81-11ea-89c6-dd0c8b983056.png">

If you change the link color the buttons still keep the original border color.

**Comment by admin-2020** [comment]
This is also fixed since that latest release.
