### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by admin-2020** [admin-2020/Admin-2020-Theme#15]
- set dark or light theme as default for everyone logged in
- set dark/light theme colours
- disable dark/light switching
- change admin logo url so it can take you to front end or support website
- the sidebar toggle should not be floating and stay pinned at the bottom
- the sidebar toggle animation isn't smooth it jumps things around off-pixel violently def needs fixing
- granular specific user permissions for more control as opposed to role permissions

**Comment by jackjumper** [comment]
• Login Page logo- to redirect to website instead of wordpress . org

**Comment by admin-2020** [comment]
Login page logo will now direct to site home page in v1.1.9 - available 25/05/2020
You can set link / accent colours since v1.1.7.3 - released
Toggle animation is fixed in v1.1.8 - released
