### ISSUE TITLE
Yoast Seo Toggle box to minimise boxes is missing

### ISSUE THREAD

**Issue by admin-2020** [admin-2020/Admin-2020-Theme#16]

**Comment by gegeor** [comment]
Hi
Not only Yoast Seo  but  all the  wp woocommerce  default  toggle boxes is missing: product short description, reviews, product data

**Comment by aldingamedia** [comment]
The toggle/minimise button also doesn't show correctly for The SEO Framework, Oxygen Builder, ACF.

**Comment by admin-2020** [comment]
Toggle function has been fixed now, this was a WP core toggle option so any plugin using it wouldn't show minimise properly. Will be available in the next release!
