### ISSUE TITLE
Woocommerce settings

### ISSUE THREAD

**Issue by ijmalakbar** [admin-2020/Admin-2020-Theme#21]
![FireShot Capture 108 - WooCommerce settings ‹ Legasi Store — WordPress - legasi store](https://user-images.githubusercontent.com/65610928/82341932-9c989680-9a23-11ea-8ac5-c85c5a4985e4.png)

Tabs woocommerce not in good arrangement. And i cant delete the shipping options

**Comment by admin-2020** [comment]
This was fixed in v1.1.7.3
