### ISSUE TITLE
User Menu Access

### ISSUE THREAD

**Issue by jackjumper** [admin-2020/Admin-2020-Theme#22]
Under the settings of the User Menus we are trying to hide access to several items for some users but its not working. When accessing the user roles we still see menu items that shouldn't be visible. Please advice, thanks!

**Comment by admin-2020** [comment]
Just to check, do you have any other plugins installed that control user access or rearrange the menu?

**Comment by jackjumper** [comment]
At the time no, now I'm using Adminimize.

**Comment by admin-2020** [comment]
What roles where you trying to do this with? Having troubling replicating the bug

**Comment by admin-2020** [comment]
Scrap that, the problem was caused by roles with more than word in them, "shop manager" for example. Fix will be available in the next release 1.2.0
