### ISSUE TITLE
Overview Page - Total Post 

### ISSUE THREAD

**Issue by jackjumper** [admin-2020/Admin-2020-Theme#23]
On the overview page its giving us a number of post that its inaccurate. Its saying that we have 189 post when we have 0. We know for a fact that our clients are going to be puzzled when they see this, please advice. Thank you.

<img width="450" alt="Screen Shot 2020-05-20 at 11 51 25 AM" src="https://user-images.githubusercontent.com/33066879/82474480-bd4b0580-9a90-11ea-8b96-3e1df0314aaf.png">

**Comment by admin-2020** [comment]
Hey, thanks for logging this. This actually counts all custom post types too, do you have any setup? It might need a tweak to the query.

**Comment by jackjumper** [comment]
No, no custom post. Just 8 pages and 15 woocommerce products.

**Comment by admin-2020** [comment]
This has been fixed in the next release v1.1.9 - will be available tomorrow.
