### ISSUE TITLE
Unusable Gutenberg new post/article

### ISSUE THREAD

**Issue by LeoSeabra** [admin-2020/Admin-2020-Theme#24]
The top buttons are gone.

![2020-05-21_11h58_31](https://user-images.githubusercontent.com/65295381/82553071-4464b000-9b5b-11ea-9f36-aea7299c0850.jpg)

**Comment by admin-2020** [comment]
Hey, can I ask what theme you have installed?

**Comment by LeoSeabra** [comment]
Divi. 

This is from a different installation (also with Divi):

![2020-05-21_13h57_22](https://user-images.githubusercontent.com/65295381/82561775-dc6a9580-9b6b-11ea-97aa-62845698da79.jpg)
![2020-05-21_13h57_31](https://user-images.githubusercontent.com/65295381/82561780-dd9bc280-9b6b-11ea-8cba-7612066a8da8.jpg)
![2020-05-21_13h57_53](https://user-images.githubusercontent.com/65295381/82561783-dd9bc280-9b6b-11ea-86bc-012724b3b41e.jpg)

**Comment by admin-2020** [comment]
Ok, looks like it might be some extra css from DIVI causing a conflict. Will look into it

**Comment by admin-2020** [comment]
This should be fixed in version 1.1.8 - can you check and let me know? Everything looks good on our end

**Comment by LeoSeabra** [comment]
Almost... just a couple of issues:

![2020-05-23_15h03_53](https://user-images.githubusercontent.com/65295381/82733032-f2fa2380-9d08-11ea-8a13-6653d871e5ae.jpg)


![2020-05-23_15h02_54](https://user-images.githubusercontent.com/65295381/82733029-ee356f80-9d08-11ea-907b-432a1b15d62f.jpg)

**Comment by admin-2020** [comment]
Hey, all of the above should be fixed in tomorrows release (1.1.9) - have a check and let me know!

Cheers,

Mark

**Comment by LeoSeabra** [comment]
Not so fast, admin-2020!

![2020-05-27_18h36_52](https://user-images.githubusercontent.com/65295381/83054035-a89ade80-a049-11ea-998d-3f1d9be25375.jpg)

**Comment by admin-2020** [comment]
Both are fixed, will be available in 1.2.0 coming later today!

**Comment by admin-2020** [comment]
Going to close this issue but if you find any other related Gutenburg issues feel free to reopen!
