### ISSUE TITLE
Vivaldi related issue

### ISSUE THREAD

**Issue by LeoSeabra** [admin-2020/Admin-2020-Theme#27]
On Vivaldi browser (Win10), clicking on the middle of these buttons doesn't work, it has to be on the edges.

![2020-05-25_09h32_48](https://user-images.githubusercontent.com/65295381/82794995-45ebec00-9e6b-11ea-92f5-dc0b09035c13.jpg)

**Comment by admin-2020** [comment]
Closing this for now as Vivaldi is not a browser we support, will reopen if this changes.
